# Generated by Django 5.1.4 on 2025-01-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
